# Generated by Django 5.2.5 on 2025-09-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='someone',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='someone',
            name='fullName',
            field=models.CharField(default=25, max_length=100),
            preserve_default=False,
        ),
    ]
